index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /ultimas
        permanent: true
    ##controller: App\Controller\PublicacionController::index
